-- 0004_first_proof_sources.sql
-- Reviewed first-proof source catalog for Workstream 4 live corpus proof.
--
-- These rows are source configuration only. The reviewed first-proof corpus rows
-- (source_documents -> claims -> claim_evidence -> fact_versions) are applied by
-- scripts/dev/backfill-first-proof-corpus.mjs against the intended runtime DB.

INSERT INTO sources (
    id,
    slug,
    name,
    description,
    source_type,
    adapter_name,
    adapter_config,
    run_cadence_seconds,
    license_spdx,
    redistribution_allowed,
    summary_allowed,
    citation_only,
    license_notes,
    rate_limit_requests_per_minute,
    is_active,
    is_paused,
    metadata
) VALUES
(
    '00000000-0000-4400-8400-000000000101',
    'first-proof-openai-news',
    'First Proof — OpenAI News',
    'Reviewed official OpenAI announcements for ChatGPT and GPT-4 Turbo first-proof coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://openai.com/news/rss.xml"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official OpenAI public announcement pages. Store only derived summaries and citations unless terms are reviewed for raw redistribution.',
    30,
    true,
    false,
    '{"source_class":"model_provider","topic_cluster":"frontier_llms","corpus_taxonomy":"ai_history","corpus_track":"first_proof"}'::jsonb
),
(
    '00000000-0000-4400-8400-000000000102',
    'first-proof-anthropic-claude-news',
    'First Proof — Anthropic Claude News',
    'Reviewed official Anthropic announcement for Claude first-proof coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://www.anthropic.com/news/rss.xml"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official Anthropic public announcement pages. Store only derived summaries and citations unless terms are reviewed for raw redistribution.',
    30,
    true,
    false,
    '{"source_class":"model_provider","topic_cluster":"frontier_llms","corpus_taxonomy":"ai_history","corpus_track":"first_proof"}'::jsonb
),
(
    '00000000-0000-4400-8400-000000000106',
    'first-proof-anthropic-mcp-news',
    'First Proof — Anthropic MCP News',
    'Reviewed official Anthropic announcement for Model Context Protocol first-proof coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://www.anthropic.com/news/rss.xml"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official Anthropic public announcement pages. Store only derived summaries and citations unless terms are reviewed for raw redistribution.',
    30,
    true,
    false,
    '{"source_class":"protocol","topic_cluster":"model_context_protocol","corpus_taxonomy":"ai_history","corpus_track":"first_proof"}'::jsonb
),
(
    '00000000-0000-4400-8400-000000000103',
    'first-proof-gemini-research',
    'First Proof — Gemini Research',
    'Reviewed Gemini technical report source for research-class first-proof coverage.',
    'research',
    'arxiv_v1',
    '{"search_terms":["Gemini A Family of Highly Capable Multimodal Models"],"categories":["cs.CL","cs.AI"],"batch_size":"10"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'arXiv abstract-first source; full paper redistribution is not assumed.',
    30,
    true,
    false,
    '{"source_class":"research","topic_cluster":"frontier_llms","corpus_taxonomy":"ai_history","corpus_track":"first_proof"}'::jsonb
),
(
    '00000000-0000-4400-8400-000000000104',
    'first-proof-llama-registry',
    'First Proof — Llama Registry',
    'Reviewed Hugging Face registry rows for Meta Llama first-proof coverage.',
    'registry',
    'registry_releases_v1',
    '{"huggingface_models":["meta-llama/Meta-Llama-3-8B","meta-llama/Meta-Llama-3-70B"]}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Hugging Face model metadata and model cards have per-model terms; raw redistribution is not assumed.',
    30,
    true,
    false,
    '{"source_class":"registry","topic_cluster":"open_weight_models","corpus_taxonomy":"ai_history","corpus_track":"first_proof"}'::jsonb
),
(
    '00000000-0000-4400-8400-000000000105',
    'first-proof-meta-llama-news',
    'First Proof — Meta Llama News',
    'Reviewed official Meta Llama announcement for open-weight first-proof coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://ai.meta.com/blog/rss/"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official Meta AI public announcement page. Store only derived summaries and citations unless terms are reviewed for raw redistribution.',
    30,
    true,
    false,
    '{"source_class":"release_notes","topic_cluster":"open_weight_models","corpus_taxonomy":"ai_history","corpus_track":"first_proof"}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    source_type = EXCLUDED.source_type,
    adapter_name = EXCLUDED.adapter_name,
    adapter_config = EXCLUDED.adapter_config,
    license_spdx = EXCLUDED.license_spdx,
    redistribution_allowed = EXCLUDED.redistribution_allowed,
    summary_allowed = EXCLUDED.summary_allowed,
    citation_only = EXCLUDED.citation_only,
    license_notes = EXCLUDED.license_notes,
    rate_limit_requests_per_minute = EXCLUDED.rate_limit_requests_per_minute,
    is_active = EXCLUDED.is_active,
    is_paused = EXCLUDED.is_paused,
    metadata = EXCLUDED.metadata,
    updated_at = now();
