-- 0005_broad_corpus_sources.sql
-- Reviewed broad-corpus source catalog for Workstream 4 live-full proof.
--
-- These rows are source configuration only. The reviewed broad-corpus rows
-- (source_documents -> claims -> claim_evidence -> fact_versions) are applied by
-- scripts/dev/backfill-broad-corpus-proof.mjs against the intended runtime DB.

INSERT INTO sources (
    id,
    slug,
    name,
    description,
    source_type,
    adapter_name,
    adapter_config,
    run_cadence_seconds,
    license_spdx,
    redistribution_allowed,
    summary_allowed,
    citation_only,
    license_notes,
    rate_limit_requests_per_minute,
    is_active,
    is_paused,
    metadata
) VALUES
(
    '00000000-0000-4500-8500-000000000101',
    'broad-proof-model-provider-news',
    'Broad Proof - Model Provider News',
    'Reviewed official model-provider announcements for broad AI-history coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://openai.com/news/rss.xml","https://www.anthropic.com/news/rss.xml"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official public model-provider announcements. Store only reviewed summaries and citations unless raw redistribution terms are reviewed.',
    30,
    true,
    false,
    '{"source_class":"model_provider","topic_cluster":"frontier_llms","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    '00000000-0000-4500-8500-000000000102',
    'broad-proof-research-arxiv',
    'Broad Proof - Research arXiv',
    'Reviewed arXiv research abstracts for broad AI-history coverage.',
    'research',
    'arxiv_v1',
    '{"search_terms":["FlashAttention","Segment Anything","Direct Preference Optimization","QLoRA"],"categories":["cs.AI","cs.CL","cs.LG","cs.CV"],"batch_size":"10"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'arXiv abstract-first source; full paper redistribution is not assumed.',
    30,
    true,
    false,
    '{"source_class":"research","topic_cluster":"ml_research","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    '00000000-0000-4500-8500-000000000103',
    'broad-proof-release-notes',
    'Broad Proof - Release Notes',
    'Reviewed official release announcements for development-cycle and open-weight coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://openai.com/news/rss.xml","https://www.anthropic.com/news/rss.xml","https://ai.meta.com/blog/rss/"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official release pages. Store only reviewed summaries and citations unless raw redistribution terms are reviewed.',
    30,
    true,
    false,
    '{"source_class":"release_notes","topic_cluster":"development_cycles","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    '00000000-0000-4500-8500-000000000104',
    'broad-proof-benchmarks',
    'Broad Proof - Benchmarks',
    'Reviewed official benchmark result pages for broad AI-history coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://mlcommons.org/feed/"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official benchmark-result pages. Store only reviewed summaries and citations unless raw redistribution terms are reviewed.',
    30,
    true,
    false,
    '{"source_class":"benchmark","topic_cluster":"benchmarks","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    '00000000-0000-4500-8500-000000000105',
    'broad-proof-developer-ecosystem',
    'Broad Proof - Developer Ecosystem',
    'Reviewed official developer-tooling sources for broad AI-history coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://openai.com/news/rss.xml","https://www.anthropic.com/news/rss.xml"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official developer/product pages. Store only reviewed summaries and citations unless raw redistribution terms are reviewed.',
    30,
    true,
    false,
    '{"source_class":"developer_ecosystem","topic_cluster":"agent_tooling","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    '00000000-0000-4500-8500-000000000106',
    'broad-proof-infrastructure',
    'Broad Proof - Infrastructure',
    'Reviewed official AI infrastructure announcements for broad AI-history coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://blogs.nvidia.com/feed/","https://cloud.google.com/blog/rss"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official infrastructure announcement pages. Store only reviewed summaries and citations unless raw redistribution terms are reviewed.',
    30,
    true,
    false,
    '{"source_class":"infrastructure","topic_cluster":"deployment_infrastructure","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    '00000000-0000-4500-8500-000000000107',
    'broad-proof-policy-regulatory',
    'Broad Proof - Policy Regulatory',
    'Reviewed official policy and regulatory sources for broad AI-history coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://www.nist.gov/news-events/news/rss.xml"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official public policy/regulatory pages. Store only reviewed summaries and citations unless raw redistribution terms are reviewed.',
    30,
    true,
    false,
    '{"source_class":"policy_regulatory","topic_cluster":"regulation","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    '00000000-0000-4500-8500-000000000108',
    'broad-proof-protocols',
    'Broad Proof - Protocols',
    'Reviewed official protocol sources for broad AI-history coverage.',
    'api',
    'rss_feed_v1',
    '{"feed_urls":["https://modelcontextprotocol.io/llms.txt"],"language":"en"}'::jsonb,
    null,
    null,
    false,
    true,
    false,
    'Official protocol documentation pages. Store only reviewed summaries and citations unless raw redistribution terms are reviewed.',
    30,
    true,
    false,
    '{"source_class":"protocol","topic_cluster":"model_context_protocol","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
),
(
    -- Tier S (CC0): OpenAlex is the fact-redistributable scholarly spine for the
    -- research_paper / ml_research / evaluation_benchmarks clusters. Per the
    -- access-tier canon (docs/operations/source-policy.md), CC0 sets the Tier S
    -- defaults: redistribution_allowed=true, summary_allowed=true,
    -- citation_only=false. The work metadata is CC0; OpenAlex is part of the
    -- redistributable backbone, not merely a citable source.
    '00000000-0000-4500-8500-000000000109',
    'broad-proof-openalex-research',
    'Broad Proof - OpenAlex Research (CC0)',
    'OpenAlex scholarly works (CC0) for the research/benchmark clusters: dated, '
    'graph-structured works filtered to the AI/ML topic for broad AI-history coverage.',
    'api',
    'openalex_v1',
    -- Default query bounds the AI/ML corpus by the artificial-intelligence
    -- concept (OpenAlex concept C154945302) over the corpus epoch. mailto rides
    -- the OpenAlex polite pool. Operators widen concepts/topics in gated waves.
    '{"openalex_api_url":"https://api.openalex.org/works","mailto":"jamie@yrka.io","date_field":"publication","start_date":"2022-11-01","concepts":["C154945302"],"per_page":"200"}'::jsonb,
    null,
    'CC0-1.0',
    true,
    true,
    false,
    'OpenAlex data is CC0 (public domain). Tier S: facts are redistributable, not citation-only. https://docs.openalex.org/additional-help/faq',
    null,
    true,
    false,
    '{"source_class":"research_paper","topic_cluster":"ml_research","access_tier":"S","corpus_taxonomy":"ai_history","corpus_track":"broad_proof"}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    source_type = EXCLUDED.source_type,
    adapter_name = EXCLUDED.adapter_name,
    adapter_config = EXCLUDED.adapter_config,
    license_spdx = EXCLUDED.license_spdx,
    redistribution_allowed = EXCLUDED.redistribution_allowed,
    summary_allowed = EXCLUDED.summary_allowed,
    citation_only = EXCLUDED.citation_only,
    license_notes = EXCLUDED.license_notes,
    rate_limit_requests_per_minute = EXCLUDED.rate_limit_requests_per_minute,
    is_active = EXCLUDED.is_active,
    is_paused = EXCLUDED.is_paused,
    metadata = EXCLUDED.metadata,
    updated_at = now();
