emit:
  - "@typespec/openapi3"
  - "@typespec/json-schema"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/generated/openapi"
    output-file: "openapi.json"
    file-type: "json"
    openapi-versions:
      - "3.1.0"
  "@typespec/json-schema":
    emitter-output-dir: "{project-root}/generated/json-schema"
    file-type: "json"
    emitAllRefs: true
