# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-04T22:52:48+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, confloat


class ApiError(BaseModel):
    code: str
    message: str
    details: Any | None = None


class Citation(BaseModel):
    sourceDocumentId: str
    quote: str | None = None
    url: str | None = None
    publishedAt: AwareDatetime | None = None


class ClaimStatus(StrEnum):
    proposed = 'proposed'
    active = 'active'
    retracted = 'retracted'
    superseded = 'superseded'


class Confidence(BaseModel):
    score: confloat(ge=0.0, le=1.0)
    method: str | None = None


class ContradictionState(StrEnum):
    none = 'none'
    contested = 'contested'
    contradicted = 'contradicted'


class EntityType(StrEnum):
    person = 'person'
    organization = 'organization'
    place = 'place'
    role = 'role'
    office = 'office'
    product = 'product'
    event = 'event'
    concept = 'concept'
    legislation = 'legislation'
    technical_artifact = 'technical_artifact'
    source = 'source'
    dataset = 'dataset'
    jurisdiction = 'jurisdiction'


class EvidenceHit(BaseModel):
    documentId: str
    snippet: str
    score: confloat(ge=0.0)
    citation: Citation


class EvidenceResponse(BaseModel):
    hits: list[EvidenceHit]
    total: int


class ExternalId(BaseModel):
    system: str
    id: str


class FreshnessReport(BaseModel):
    target: str
    lastUpdated: AwareDatetime | None = None
    lastIngestedAt: AwareDatetime | None = None
    coverage: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='Fraction of expected sources currently covered, in [0,1].'
    )
    staleness: str | None = None


class RelationshipStatus(StrEnum):
    active = 'active'
    ended = 'ended'
    proposed = 'proposed'


class SourceDocument(BaseModel):
    id: str
    sourceId: str
    title: str | None = None
    url: str | None = None
    publishedAt: AwareDatetime | None = None
    ingestedAt: AwareDatetime
    language: str | None = None
    contentHash: str
    license: str | None = None


class SourcesResponse(BaseModel):
    sources: list[SourceDocument]


class VerificationVerdict(StrEnum):
    supported = 'supported'
    partially_supported = 'partially_supported'
    contradicted = 'contradicted'
    unverified = 'unverified'


class Claim(BaseModel):
    id: str
    subject: str
    predicate: str
    object: str
    qualifiers: Any | None = None
    normalizedText: str
    validFrom: AwareDatetime | None = Field(
        None,
        description='When the claim is/was true in the world (bitemporal valid time).',
    )
    validUntil: AwareDatetime | None = None
    recordedAt: AwareDatetime = Field(
        ...,
        description='When Intercal recorded the claim (bitemporal transaction time).',
    )
    confidence: Confidence
    status: ClaimStatus
    contradiction: ContradictionState
    evidence: list[Citation]


class ClaimVerificationResponse(BaseModel):
    claimText: str
    verdict: VerificationVerdict
    confidence: Confidence
    supportingEvidence: list[Citation]
    contradictingEvidence: list[Citation]
    asOf: AwareDatetime | None = None


class Digest(BaseModel):
    topicOrEntity: str
    tokenBudget: int | None = None
    content: str
    citations: list[Citation]
    freshness: FreshnessReport
    generatedAt: AwareDatetime


class Entity(BaseModel):
    id: str
    type: EntityType
    displayName: str
    aliases: list[str] | None = None
    externalIds: list[ExternalId] | None = None
    importance: float | None = None
    firstSeen: AwareDatetime | None = None
    lastUpdated: AwareDatetime | None = None
    state: Any | None = Field(
        None,
        description='Denormalized current state; derived from fact versions, not a source of truth.',
    )


class EntitySummary(BaseModel):
    id: str
    type: EntityType
    displayName: str


class Relationship(BaseModel):
    id: str
    type: str
    fromEntityId: str
    toEntityId: str
    validFrom: AwareDatetime | None = None
    validUntil: AwareDatetime | None = None
    recordedAt: AwareDatetime
    confidence: Confidence
    status: RelationshipStatus
    sourceDocumentIds: list[str]


class DeltaResponse(BaseModel):
    topic: str
    since: AwareDatetime
    until: AwareDatetime | None = None
    summary: Digest
    changedClaims: list[Claim]
    changedEntities: list[EntitySummary]
    confidence: Confidence
    freshness: FreshnessReport


class EntityResponse(BaseModel):
    entity: Entity
    asOf: AwareDatetime | None = None
    relationships: list[Relationship] | None = None
    facts: list[Claim] | None = None
    freshness: FreshnessReport
