# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, confloat, conint, constr


class ApiError(BaseModel):
    code: str
    message: str
    details: Any | None = None


class Citation(BaseModel):
    sourceDocumentId: str
    quote: str | None = None
    url: str | None = None
    publishedAt: AwareDatetime | None = None


class ClaimStatus(StrEnum):
    proposed = 'proposed'
    active = 'active'
    retracted = 'retracted'
    superseded = 'superseded'


class Confidence(BaseModel):
    score: confloat(ge=0.0, le=1.0)
    method: str | None = None


class ContradictionState(StrEnum):
    none = 'none'
    contested = 'contested'
    contradicted = 'contradicted'


class DeleteSubscriptionRequest(BaseModel):
    subscriptionId: str


class DispatchSubscriptionResponse(BaseModel):
    enqueued: int
    skipped: int


class EntityType(StrEnum):
    person = 'person'
    organization = 'organization'
    place = 'place'
    role = 'role'
    office = 'office'
    product = 'product'
    event = 'event'
    concept = 'concept'
    legislation = 'legislation'
    technical_artifact = 'technical_artifact'
    source = 'source'
    dataset = 'dataset'
    jurisdiction = 'jurisdiction'


class EvidenceHit(BaseModel):
    documentId: str
    snippet: str
    score: confloat(ge=0.0)
    citation: Citation


class EvidenceResponse(BaseModel):
    hits: list[EvidenceHit]
    total: int


class ExternalId(BaseModel):
    system: str
    id: str


class FeedbackConcernType(StrEnum):
    incorrect = 'incorrect'
    outdated = 'outdated'
    missing_evidence = 'missing_evidence'
    missing_coverage = 'missing_coverage'
    source_quality = 'source_quality'
    contradiction = 'contradiction'
    other = 'other'


class FeedbackTargetType(StrEnum):
    entity = 'entity'
    claim = 'claim'
    source = 'source'
    digest = 'digest'
    freshness = 'freshness'
    coverage = 'coverage'


class FreshnessReport(BaseModel):
    target: str
    lastUpdated: AwareDatetime | None = None
    lastIngestedAt: AwareDatetime | None = None
    coverage: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='Fraction of expected sources currently covered, in [0,1].'
    )
    staleness: str | None = None


class PollSubscriptionRequest(BaseModel):
    subscriptionId: str
    limit: conint(ge=1, le=100) | None = None


class RelationshipStatus(StrEnum):
    active = 'active'
    ended = 'ended'
    proposed = 'proposed'


class ReviewStatus(StrEnum):
    received = 'received'
    reviewing = 'reviewing'
    resolved = 'resolved'
    rejected = 'rejected'


class SourceDocument(BaseModel):
    id: str
    sourceId: str
    title: str | None = None
    url: str | None = None
    publishedAt: AwareDatetime | None = None
    ingestedAt: AwareDatetime
    language: str | None = None
    contentHash: str
    license: str | None = None


class SourcesResponse(BaseModel):
    sources: list[SourceDocument]


class SubscriptionDeliveryMethod(StrEnum):
    polling = 'polling'
    webhook = 'webhook'


class SubscriptionTargetKind(StrEnum):
    topic = 'topic'
    entity = 'entity'
    relationship = 'relationship'
    claim_pattern = 'claim_pattern'


class VerificationVerdict(StrEnum):
    supported = 'supported'
    partially_supported = 'partially_supported'
    contradicted = 'contradicted'
    unverified = 'unverified'


class Claim(BaseModel):
    id: str
    subject: str
    predicate: str
    object: str
    qualifiers: Any | None = None
    normalizedText: str
    validFrom: AwareDatetime | None = Field(
        None,
        description='When the claim is/was true in the world (bitemporal valid time).',
    )
    validUntil: AwareDatetime | None = None
    recordedAt: AwareDatetime = Field(
        ...,
        description='When Intercal recorded the claim (bitemporal transaction time).',
    )
    confidence: Confidence
    status: ClaimStatus
    contradiction: ContradictionState
    evidence: list[Citation]


class ClaimVerificationResponse(BaseModel):
    claimText: str
    verdict: VerificationVerdict
    confidence: Confidence
    supportingEvidence: list[Citation]
    contradictingEvidence: list[Citation]
    asOf: AwareDatetime | None = None


class Digest(BaseModel):
    topicOrEntity: str
    tokenBudget: int | None = None
    content: str
    citations: list[Citation]
    freshness: FreshnessReport
    generatedAt: AwareDatetime


class DispatchSubscriptionRequest(BaseModel):
    changeKind: SubscriptionTargetKind
    topicId: str | None = None
    entityId: str | None = None
    relationshipTypeId: str | None = None
    claimPattern: Any | None = None
    sinceDate: AwareDatetime
    untilDate: AwareDatetime | None = None


class Entity(BaseModel):
    id: str
    type: EntityType
    displayName: str
    aliases: list[str] | None = None
    externalIds: list[ExternalId] | None = None
    importance: float | None = None
    firstSeen: AwareDatetime | None = None
    lastUpdated: AwareDatetime | None = None
    state: Any | None = Field(
        None,
        description='Denormalized current state; derived from fact versions, not a source of truth.',
    )


class EntitySummary(BaseModel):
    id: str
    type: EntityType
    displayName: str


class FeedbackRequest(BaseModel):
    targetType: FeedbackTargetType
    targetId: constr(min_length=1, max_length=256)
    concernType: FeedbackConcernType
    summary: constr(min_length=1, max_length=240)
    details: constr(max_length=4000) | None = None


class Relationship(BaseModel):
    id: str
    type: str
    fromEntityId: str
    toEntityId: str
    validFrom: AwareDatetime | None = None
    validUntil: AwareDatetime | None = None
    recordedAt: AwareDatetime
    confidence: Confidence
    status: RelationshipStatus
    sourceDocumentIds: list[str]


class ReviewRecord(BaseModel):
    id: str
    targetType: FeedbackTargetType
    targetId: str
    concernType: FeedbackConcernType
    status: ReviewStatus
    summary: str
    details: str | None = None
    createdAt: AwareDatetime


class SubscriptionNotification(BaseModel):
    id: str
    subscriptionId: str
    changeKind: SubscriptionTargetKind
    targetLabel: str
    since: AwareDatetime
    until: AwareDatetime
    minImportance: confloat(ge=0.0, le=1.0)
    maxImportance: confloat(ge=0.0, le=1.0)
    tokenBudget: int
    payload: Any
    status: str
    createdAt: AwareDatetime
    deliveredAt: AwareDatetime | None = None


class SubscriptionNotificationsResponse(BaseModel):
    notifications: list[SubscriptionNotification]


class SubscriptionTarget(BaseModel):
    kind: SubscriptionTargetKind
    topicId: str | None = None
    entityId: str | None = None
    relationshipTypeId: str | None = None
    claimPattern: Any | None = None


class CreateSubscriptionRequest(BaseModel):
    target: SubscriptionTarget
    deliveryMethod: SubscriptionDeliveryMethod
    webhookUrl: str | None = None
    webhookSecret: str | None = Field(
        None,
        description='Plaintext webhook secret accepted only on create; the API stores a hash and never returns it.',
    )
    minImportance: confloat(ge=0.0, le=1.0) | None = None
    tokenBudget: conint(ge=200, le=8000) | None = None
    metadata: Any | None = None


class DeltaResponse(BaseModel):
    topic: str
    since: AwareDatetime
    until: AwareDatetime | None = None
    summary: Digest
    changedClaims: list[Claim]
    changedEntities: list[EntitySummary]
    confidence: Confidence
    freshness: FreshnessReport


class EntityResponse(BaseModel):
    entity: Entity
    asOf: AwareDatetime | None = None
    relationships: list[Relationship] | None = None
    facts: list[Claim] | None = None
    freshness: FreshnessReport


class FeedbackResponse(BaseModel):
    review: ReviewRecord


class Subscription(BaseModel):
    id: str
    target: SubscriptionTarget
    deliveryMethod: SubscriptionDeliveryMethod
    webhookUrl: str | None = None
    minImportance: confloat(ge=0.0, le=1.0)
    tokenBudget: int
    isActive: bool
    lastDeliveredAt: AwareDatetime | None = None
    lastCheckedAt: AwareDatetime | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class SubscriptionResponse(BaseModel):
    subscription: Subscription


class SubscriptionsResponse(BaseModel):
    subscriptions: list[Subscription]
